PRAGMA user_version = 1;

CREATE TABLE IF NOT EXISTS USERS (
  PHONE_NUMBER TEXT PRIMARY KEY,
  NICKNAME TEXT NOT NULL COLLATE NOCASE UNIQUE
    CHECK (LENGTH(NICKNAME) BETWEEN 3 AND 20)
    CHECK (NICKNAME NOT GLOB '*[^A-Za-z0-9_]*'),
  CREATED_AT TEXT NOT NULL DEFAULT (STRFTIME('%Y-%m-%dT%H:%M:%fZ', 'now')),
  IS_SEED INTEGER NOT NULL DEFAULT 0 CHECK (IS_SEED IN (0, 1))
) STRICT;

CREATE TABLE IF NOT EXISTS SESSIONS (
  TOKEN TEXT PRIMARY KEY,
  PHONE_NUMBER TEXT NOT NULL REFERENCES USERS(PHONE_NUMBER) ON DELETE CASCADE,
  CREATED_AT TEXT NOT NULL DEFAULT (STRFTIME('%Y-%m-%dT%H:%M:%fZ', 'now')),
  LAST_SEEN_AT TEXT NOT NULL DEFAULT (STRFTIME('%Y-%m-%dT%H:%M:%fZ', 'now')),
  IS_SEED INTEGER NOT NULL DEFAULT 0 CHECK (IS_SEED IN (0, 1))
) STRICT;

CREATE TABLE IF NOT EXISTS PLACES (
  ID TEXT PRIMARY KEY,
  NAME TEXT NOT NULL,
  SLUG TEXT NOT NULL UNIQUE,
  PARENT_PLACE_ID TEXT REFERENCES PLACES(ID) ON DELETE RESTRICT,
  GEOJSON TEXT NOT NULL CHECK (JSON_VALID(GEOJSON)),
  CREATED_AT TEXT NOT NULL DEFAULT (STRFTIME('%Y-%m-%dT%H:%M:%fZ', 'now')),
  IS_SEED INTEGER NOT NULL DEFAULT 0 CHECK (IS_SEED IN (0, 1))
) STRICT;

CREATE TABLE IF NOT EXISTS PLACE_HIERARCHY (
  ANCESTOR_PLACE_ID TEXT NOT NULL REFERENCES PLACES(ID) ON DELETE CASCADE,
  DESCENDANT_PLACE_ID TEXT NOT NULL REFERENCES PLACES(ID) ON DELETE CASCADE,
  DEPTH INTEGER NOT NULL CHECK (DEPTH >= 0),
  IS_SEED INTEGER NOT NULL DEFAULT 0 CHECK (IS_SEED IN (0, 1)),
  PRIMARY KEY (ANCESTOR_PLACE_ID, DESCENDANT_PLACE_ID)
) STRICT;

CREATE TABLE IF NOT EXISTS SETTINGS (
  ID INTEGER PRIMARY KEY CHECK (ID = 1),
  FORCE_PLACE_ID TEXT REFERENCES PLACES(ID) ON DELETE SET NULL,
  UPDATED_AT TEXT NOT NULL DEFAULT (STRFTIME('%Y-%m-%dT%H:%M:%fZ', 'now')),
  IS_SEED INTEGER NOT NULL DEFAULT 0 CHECK (IS_SEED IN (0, 1))
) STRICT;

CREATE TABLE IF NOT EXISTS USER_VISITS (
  ID TEXT PRIMARY KEY,
  PLACE_ID TEXT NOT NULL REFERENCES PLACES(ID) ON DELETE CASCADE,
  PHONE_NUMBER TEXT NOT NULL REFERENCES USERS(PHONE_NUMBER) ON DELETE CASCADE,
  ENTERED_AT TEXT NOT NULL DEFAULT (STRFTIME('%Y-%m-%dT%H:%M:%fZ', 'now')),
  LEFT_AT TEXT,
  IS_SEED INTEGER NOT NULL DEFAULT 0 CHECK (IS_SEED IN (0, 1)),
  CHECK (LEFT_AT IS NULL OR LEFT_AT >= ENTERED_AT)
) STRICT;

CREATE TABLE IF NOT EXISTS USER_PLACE_RANK (
  PLACE_ID TEXT NOT NULL REFERENCES PLACES(ID) ON DELETE CASCADE,
  PHONE_NUMBER TEXT NOT NULL REFERENCES USERS(PHONE_NUMBER) ON DELETE CASCADE,
  RANK TEXT NOT NULL DEFAULT 'belong' CHECK (RANK IN ('visitor', 'belong')),
  VISIT_COUNT INTEGER NOT NULL DEFAULT 1 CHECK (VISIT_COUNT >= 1),
  UPDATED_AT TEXT NOT NULL DEFAULT (STRFTIME('%Y-%m-%dT%H:%M:%fZ', 'now')),
  IS_SEED INTEGER NOT NULL DEFAULT 0 CHECK (IS_SEED IN (0, 1)),
  PRIMARY KEY (PLACE_ID, PHONE_NUMBER)
) STRICT;

CREATE TABLE IF NOT EXISTS MEDIA (
  ID TEXT PRIMARY KEY,
  HASH TEXT NOT NULL UNIQUE,
  TYPE TEXT NOT NULL CHECK (TYPE IN ('image', 'video')),
  DOMINANT_COLOR TEXT,
  THUMB_URL TEXT,
  MEDIUM_URL TEXT,
  ORIGINAL_URL TEXT,
  CREATED_AT TEXT NOT NULL DEFAULT (STRFTIME('%Y-%m-%dT%H:%M:%fZ', 'now')),
  IS_SEED INTEGER NOT NULL DEFAULT 0 CHECK (IS_SEED IN (0, 1))
) STRICT;

CREATE TABLE IF NOT EXISTS KNOCKS (
  ID TEXT PRIMARY KEY,
  PLACE_ID TEXT NOT NULL REFERENCES PLACES(ID) ON DELETE CASCADE,
  PHONE_NUMBER TEXT NOT NULL REFERENCES USERS(PHONE_NUMBER) ON DELETE CASCADE,
  TYPE TEXT NOT NULL CHECK (TYPE IN ('text', 'image', 'video')),
  CONTENT TEXT,
  MEDIA_ID TEXT REFERENCES MEDIA(ID) ON DELETE SET NULL,
  CREATED_AT TEXT NOT NULL DEFAULT (STRFTIME('%Y-%m-%dT%H:%M:%fZ', 'now')),
  IS_SEED INTEGER NOT NULL DEFAULT 0 CHECK (IS_SEED IN (0, 1)),
  CHECK (
    (TYPE = 'text' AND CONTENT IS NOT NULL AND MEDIA_ID IS NULL)
    OR (TYPE IN ('image', 'video') AND MEDIA_ID IS NOT NULL)
  )
) STRICT;

CREATE TABLE IF NOT EXISTS MOMENTS (
  ID TEXT PRIMARY KEY,
  PLACE_ID TEXT NOT NULL REFERENCES PLACES(ID) ON DELETE CASCADE,
  PHONE_NUMBER TEXT NOT NULL REFERENCES USERS(PHONE_NUMBER) ON DELETE CASCADE,
  MEDIA_ID TEXT NOT NULL REFERENCES MEDIA(ID) ON DELETE RESTRICT,
  CAPTION TEXT CHECK (CAPTION IS NULL OR LENGTH(CAPTION) <= 100),
  PRESENCE_COUNT INTEGER NOT NULL DEFAULT 0 CHECK (PRESENCE_COUNT >= 0),
  STATUS TEXT NOT NULL DEFAULT 'live' CHECK (STATUS IN ('live', 'engraved')),
  CREATED_AT TEXT NOT NULL DEFAULT (STRFTIME('%Y-%m-%dT%H:%M:%fZ', 'now')),
  IS_SEED INTEGER NOT NULL DEFAULT 0 CHECK (IS_SEED IN (0, 1))
) STRICT;

CREATE TABLE IF NOT EXISTS MOMENT_PRESENCE (
  MOMENT_ID TEXT NOT NULL REFERENCES MOMENTS(ID) ON DELETE CASCADE,
  PHONE_NUMBER TEXT NOT NULL REFERENCES USERS(PHONE_NUMBER) ON DELETE CASCADE,
  CONFIRMED_AT TEXT NOT NULL DEFAULT (STRFTIME('%Y-%m-%dT%H:%M:%fZ', 'now')),
  IS_SEED INTEGER NOT NULL DEFAULT 0 CHECK (IS_SEED IN (0, 1)),
  PRIMARY KEY (MOMENT_ID, PHONE_NUMBER)
) STRICT;

CREATE TABLE IF NOT EXISTS MEMORIES (
  ID TEXT PRIMARY KEY,
  PLACE_ID TEXT NOT NULL REFERENCES PLACES(ID) ON DELETE CASCADE,
  TITLE TEXT NOT NULL,
  COVER_MEDIA_ID TEXT NOT NULL REFERENCES MEDIA(ID) ON DELETE RESTRICT,
  PRESENCE_TOTAL INTEGER NOT NULL DEFAULT 0 CHECK (PRESENCE_TOTAL >= 0),
  PHOTO_COUNT INTEGER NOT NULL DEFAULT 1 CHECK (PHOTO_COUNT >= 1),
  ENGRAVED_AT TEXT NOT NULL DEFAULT (STRFTIME('%Y-%m-%dT%H:%M:%fZ', 'now')),
  IS_SEED INTEGER NOT NULL DEFAULT 0 CHECK (IS_SEED IN (0, 1))
) STRICT;

-- The specification names this foreign key MOMENT_ID. It identifies a MEMORIES row.
CREATE TABLE IF NOT EXISTS MEMORY_MEDIA (
  MOMENT_ID TEXT NOT NULL REFERENCES MEMORIES(ID) ON DELETE CASCADE,
  MEDIA_ID TEXT NOT NULL REFERENCES MEDIA(ID) ON DELETE RESTRICT,
  ORDER_INDEX INTEGER NOT NULL CHECK (ORDER_INDEX >= 0),
  IS_SEED INTEGER NOT NULL DEFAULT 0 CHECK (IS_SEED IN (0, 1)),
  PRIMARY KEY (MOMENT_ID, MEDIA_ID),
  UNIQUE (MOMENT_ID, ORDER_INDEX)
) STRICT;

CREATE TABLE IF NOT EXISTS MEMORY_REACTIONS (
  MOMENT_ID TEXT NOT NULL REFERENCES MEMORIES(ID) ON DELETE CASCADE,
  PHONE_NUMBER TEXT NOT NULL REFERENCES USERS(PHONE_NUMBER) ON DELETE CASCADE,
  TYPE TEXT NOT NULL CHECK (TYPE IN ('stone', 'word')),
  COMMENT_TEXT TEXT,
  CREATED_AT TEXT NOT NULL DEFAULT (STRFTIME('%Y-%m-%dT%H:%M:%fZ', 'now')),
  IS_SEED INTEGER NOT NULL DEFAULT 0 CHECK (IS_SEED IN (0, 1)),
  PRIMARY KEY (MOMENT_ID, PHONE_NUMBER, TYPE),
  CHECK (
    (TYPE = 'stone' AND COMMENT_TEXT IS NULL)
    OR (TYPE = 'word' AND COMMENT_TEXT IS NOT NULL AND LENGTH(COMMENT_TEXT) <= 100)
  )
) STRICT;

CREATE TABLE IF NOT EXISTS MEMORY_PARTICIPANTS (
  MOMENT_ID TEXT NOT NULL REFERENCES MEMORIES(ID) ON DELETE CASCADE,
  PHONE_NUMBER TEXT NOT NULL REFERENCES USERS(PHONE_NUMBER) ON DELETE CASCADE,
  ROLE TEXT NOT NULL CHECK (ROLE IN ('contributor', 'witness')),
  CREATED_AT TEXT NOT NULL DEFAULT (STRFTIME('%Y-%m-%dT%H:%M:%fZ', 'now')),
  IS_SEED INTEGER NOT NULL DEFAULT 0 CHECK (IS_SEED IN (0, 1)),
  PRIMARY KEY (MOMENT_ID, PHONE_NUMBER)
) STRICT;

CREATE INDEX IF NOT EXISTS KNOCKS_PLACE_CREATED_AT_IDX
  ON KNOCKS(PLACE_ID, CREATED_AT);
CREATE INDEX IF NOT EXISTS MOMENTS_PLACE_CREATED_AT_IDX
  ON MOMENTS(PLACE_ID, CREATED_AT);
CREATE INDEX IF NOT EXISTS MEMORIES_PLACE_ENGRAVED_AT_IDX
  ON MEMORIES(PLACE_ID, ENGRAVED_AT DESC);

CREATE INDEX IF NOT EXISTS SESSIONS_PHONE_NUMBER_IDX
  ON SESSIONS(PHONE_NUMBER);
CREATE INDEX IF NOT EXISTS PLACE_HIERARCHY_DESCENDANT_IDX
  ON PLACE_HIERARCHY(DESCENDANT_PLACE_ID, DEPTH);
CREATE UNIQUE INDEX IF NOT EXISTS USER_VISITS_ONE_OPEN_IDX
  ON USER_VISITS(PHONE_NUMBER) WHERE LEFT_AT IS NULL;
CREATE INDEX IF NOT EXISTS USER_VISITS_PLACE_ENTERED_AT_IDX
  ON USER_VISITS(PLACE_ID, ENTERED_AT);
CREATE INDEX IF NOT EXISTS USER_PLACE_RANK_PHONE_NUMBER_IDX
  ON USER_PLACE_RANK(PHONE_NUMBER, PLACE_ID);
CREATE INDEX IF NOT EXISTS MOMENT_PRESENCE_PHONE_NUMBER_IDX
  ON MOMENT_PRESENCE(PHONE_NUMBER, MOMENT_ID);
CREATE INDEX IF NOT EXISTS MEMORY_PARTICIPANTS_PHONE_NUMBER_IDX
  ON MEMORY_PARTICIPANTS(PHONE_NUMBER, MOMENT_ID);
